/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-digidoc.h
 #	source generated by 4D Plugin Wizard
 #	Project : digidoc
 #	author : miyako
 #	2020/10/23
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_DIGIDOC_H
#define PLUGIN_DIGIDOC_H

#include "4DPluginAPI.h"

#include <log.h>
#include <Conf.h>
#include <Container.h>
#include <XmlConf.h>
#include <crypto/Digest.h>
#include <crypto/PKCS12Signer.h>
#include <crypto/PKCS11Signer.h>
#include <crypto/TSL.h>
//#include <crypto/X509Cert.h>
//#include "crypto/OpenSSLHelpers.h"

#ifdef _WIN32
#include <Windows.h>
#include <conio.h>
#else
#include <cstring>
#include <unistd.h>
#endif

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <functional>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>

#pragma mark -

void digidoc_sign(PA_PluginParameters params);
void digidoc_verify(PA_PluginParameters params);

#endif /* PLUGIN_DIGIDOC_H */
